#!/usr/bin/env bash
# One-step setup for ARGUS.
#
# Three macOS-specific gotchas this script defends against:
#
#   1. iCloud Drive clones the venv. ~/Desktop is iCloud-synced on most
#      Macs. Concurrent writes to .venv/ trigger conflict-renames like
#      `.venv/lib/python3.13 2/`, splitting installed packages across
#      two trees so `import typer` randomly fails.
#      → bootstrap.sh keeps the venv inside `~/Library/Caches/argus/venv`
#        (out of iCloud's reach) via `UV_PROJECT_ENVIRONMENT`.
#
#   2. uv stamps every file in .venv/ with the macOS UF_HIDDEN flag.
#      Python 3.13's site.py silently skips `.pth` files that carry it,
#      so any editable install never registers the project on sys.path.
#      → postsync.sh strips the flag from every .pth as a fallback.
#
#   3. uv reinstalls the project editably on every `uv sync` / `uv run`,
#      undoing any fixup we apply. With UV_NO_EDITABLE=1 the project is
#      installed as a regular copied package — no .pth, no hidden flag
#      issue, just `import argus` finding the package directly in
#      site-packages.
#
# The script also installs a `~/.local/bin/argus` shim so you can call
# `argus` from anywhere without the `./argus.sh` prefix dance. If you
# already have an `argus` on PATH that points at a missing target (e.g.
# a leftover from a previous project), it's replaced — broken shims help
# nobody. A real, working `argus` is left alone unless you pass --force.
set -euo pipefail

FORCE=0
INSTALL_SHIM=1
for arg in "$@"; do
  case "$arg" in
    --force)       FORCE=1 ;;
    --no-shim)     INSTALL_SHIM=0 ;;
    -h|--help)
      echo "Usage: ./bootstrap.sh [--force] [--no-shim]"
      echo "  --force    Replace an existing ~/.local/bin/argus even if it works"
      echo "  --no-shim  Skip installing the ~/.local/bin/argus shim"
      exit 0
      ;;
  esac
done

ROOT="$(cd "$(dirname "$0")" && pwd)"
VENV="${ARGUS_VENV:-$HOME/Library/Caches/argus/venv}"

echo "  ⟨◇⟩  project: $ROOT"
echo "  ⟨◇⟩  venv:    $VENV  (out of iCloud's reach)"

# ── System-level prerequisites ────────────────────────────────────────────
# ffmpeg powers Telegram voice-bubble re-encoding (Opus → OGG container).
# Without it, voice messages fall back to plain audio attachments — works,
# but loses the in-line waveform UI on Telegram. Install if brew is present.
if [[ "$(uname)" == "Darwin" ]] && command -v brew >/dev/null 2>&1; then
  if ! command -v ffmpeg >/dev/null 2>&1; then
    echo "  ⟨◇⟩  installing ffmpeg (needed for Telegram voice bubbles)…"
    brew install ffmpeg >/dev/null 2>&1 && echo "  ⟨◇⟩  ✓ ffmpeg installed" \
      || echo "  ⟨◇⟩  ⚠ ffmpeg install failed — voice bubbles will use fallback"
  fi
fi

export UV_PROJECT_ENVIRONMENT="$VENV"
export UV_NO_EDITABLE=1

mkdir -p "$(dirname "$VENV")"
cd "$ROOT"
uv sync --extra voice --extra voice-wake --extra office --extra cron --extra vault --extra api

scripts/postsync.sh

# Refresh the local .venv symlink so editor tools / IDEs still find a venv
# at the project root. Safe to delete if you don't want it.
rm -rf "$ROOT/.venv"
ln -s "$VENV" "$ROOT/.venv"

# ── Global `argus` shim ────────────────────────────────────────────────
if [[ "$INSTALL_SHIM" == "1" ]]; then
  SHIM_DIR="$HOME/.local/bin"
  SHIM="$SHIM_DIR/argus"
  mkdir -p "$SHIM_DIR"

  install_shim() {
    cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# ARGUS launcher — generated by $ROOT/bootstrap.sh
# Run \`./bootstrap.sh\` from the project root to regenerate.
#
# Calls the venv's argus binary DIRECTLY — does NOT use \`uv run\` because
# uv run re-syncs the project on every invocation, which uninstalls
# anything from optional extras (voice, voice-wake, office) that aren't
# in the default deps. The venv is already populated by bootstrap.sh.
ARGUS_BIN="$VENV/bin/argus"
if [[ ! -x "\$ARGUS_BIN" ]]; then
  echo "ARGUS not installed. Run: cd $ROOT && ./bootstrap.sh" >&2
  exit 1
fi
exec "\$ARGUS_BIN" "\$@"
EOF
    chmod +x "$SHIM"
    echo "  ⟨◇⟩  installed $SHIM"
  }

  if [[ -e "$SHIM" || -L "$SHIM" ]]; then
    # Test whether the existing shim actually works.
    if "$SHIM" --version >/dev/null 2>&1 && [[ "$FORCE" != "1" ]]; then
      echo "  ⟨◇⟩  $SHIM already works — leaving it alone (use --force to replace)"
    else
      echo "  ⟨◇⟩  replacing broken/stale shim at $SHIM"
      rm -f "$SHIM"
      install_shim
    fi
  else
    install_shim
  fi

  case ":$PATH:" in
    *":$SHIM_DIR:"*) ;;
    *)
      echo "  ⚠  $SHIM_DIR is not on your PATH — add this to ~/.zshrc:"
      echo "         export PATH=\"\$HOME/.local/bin:\$PATH\""
      ;;
  esac
fi

cat <<EOF

  ✓  ready. From any directory:

       argus                        # banner + chat REPL
       argus demo                   # narrated tour of every screen
       argus setup                  # onboarding wizard
       argus doctor --all-green

  Or from this project root, the wrapper still works:

       ./argus.sh demo
EOF
